// This file mimics the bindings generated by `wails generate`.
// It allows the frontend to invoke Go methods without requiring the CLI at build time.

export function ServerInfo() {
    return window?.go?.app?.App?.ServerInfo?.() ?? Promise.reject(new Error("ServerInfo bridge not initialised"));
}

export function EnvironmentInfo() {
    return window?.go?.app?.App?.EnvironmentInfo?.() ?? Promise.reject(new Error("EnvironmentInfo bridge not initialised"));
}

export function OpenPath(arg1: string) {
    return window?.go?.app?.App?.OpenPath?.(arg1) ?? Promise.reject(new Error("OpenPath bridge not initialised"));
}
