// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CoreService spawns and supervises the px backend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Arm prepares a fresh callback "pulse" channel before px (re)starts. Call
 * this immediately before spawning px (directly or via the service).
 * @returns {$CancellablePromise<void>}
 */
export function Arm() {
    return $Call.ByID(2539186389);
}

/**
 * Await blocks until the next /pxStore callback arrives (or timeout), records
 * the connection info and returns it.
 * @param {time$0.Duration} timeout
 * @returns {$CancellablePromise<$models.ConnInfo>}
 */
export function Await(timeout) {
    return $Call.ByID(3445445805, timeout).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CbAddr returns the callback server address ("host:port"). Empty until Start.
 * @returns {$CancellablePromise<string>}
 */
export function CbAddr() {
    return $Call.ByID(1747208275);
}

/**
 * GetConnInfo is bound to the frontend; it blocks (up to a timeout) until px
 * has reported its port/secret at least once, then returns the latest values.
 * @returns {$CancellablePromise<$models.ConnInfo>}
 */
export function GetConnInfo() {
    return $Call.ByID(196298313).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Home returns the px home directory.
 * @returns {$CancellablePromise<string>}
 */
export function Home() {
    return $Call.ByID(440990254);
}

/**
 * KillPx terminates the locally spawned px process (if any). px started via
 * the service is not killed here; the caller handles that through the service.
 * @returns {$CancellablePromise<void>}
 */
export function KillPx() {
    return $Call.ByID(2830636873);
}

/**
 * MarkStartedBySvc records that the current px was started via px-service.
 * @returns {$CancellablePromise<void>}
 */
export function MarkStartedBySvc() {
    return $Call.ByID(1390647494);
}

/**
 * PxPath returns the resolved px binary path.
 * @returns {$CancellablePromise<string>}
 */
export function PxPath() {
    return $Call.ByID(3778299366);
}

/**
 * RestartDirect kills any running px and spawns a fresh one directly (no
 * elevated service). Used on first start and for non-TUN restarts.
 * @returns {$CancellablePromise<$models.ConnInfo>}
 */
export function RestartDirect() {
    return $Call.ByID(4139875253).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Start launches the callback server and the px process (direct spawn), then
 * waits until px has called back with its port/secret.
 * @returns {$CancellablePromise<$models.ConnInfo>}
 */
export function Start() {
    return $Call.ByID(1409532927).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Stop terminates px and the callback server (Wails lifecycle hook).
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(315843205);
}

// Private type creation functions
const $$createType0 = $models.ConnInfo.createFrom;
