// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CoreService spawns and supervises the px backend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Arm prepares a fresh callback "pulse" channel before px (re)starts. Call
 * this immediately before spawning px (directly or via the service).
 * @returns {$CancellablePromise<void>}
 */
export function Arm() {
    return $Call.ByID(2539186389);
}

/**
 * Await blocks until the next /pxStore callback arrives (or timeout), records
 * the connection info and returns it.
 * @param {time$0.Duration} timeout
 * @returns {$CancellablePromise<$models.ConnInfo>}
 */
export function Await(timeout) {
    return $Call.ByID(3445445805, timeout).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CbAddr returns the callback server address ("host:port"). Empty until Start.
 * @returns {$CancellablePromise<string>}
 */
export function CbAddr() {
    return $Call.ByID(1747208275);
}

/**
 * ChangeConfigDir moves the data directory into <dir>/Prizrak-Box-V3, persists
 * the new location and relaunches the app — a faithful port of Electron's
 * src-electron/change.ts doChange().
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function ChangeConfigDir(dir) {
    return $Call.ByID(1633152846, dir);
}

/**
 * ConfigDir returns the current px data directory (…/Prizrak-Box-V3).
 * Mirrors Electron's `pre-config-dir`.
 * @returns {$CancellablePromise<string>}
 */
export function ConfigDir() {
    return $Call.ByID(195034246);
}

/**
 * FileIcon returns the icon of the executable at path as a PNG data URL
 * ("data:image/png;base64,…"), or "" if none could be resolved. Bound to the
 * frontend (CoreService is registered with the Wails app).
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function FileIcon(path) {
    return $Call.ByID(4194184738, path);
}

/**
 * GetConnInfo is bound to the frontend; it blocks (up to a timeout) until px
 * has reported its port/secret at least once, then returns the latest values.
 * @returns {$CancellablePromise<$models.ConnInfo>}
 */
export function GetConnInfo() {
    return $Call.ByID(196298313).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Home returns the px home directory.
 * @returns {$CancellablePromise<string>}
 */
export function Home() {
    return $Call.ByID(440990254);
}

/**
 * KillPx terminates the locally spawned px process (if any). px started via
 * the service is not killed here; the caller handles that through the service.
 * 
 * On Unix it first sends SIGINT so px can run its shutdown (which disables the
 * system proxy), then force-kills after a short grace period. On Windows it
 * kills directly.
 * @returns {$CancellablePromise<void>}
 */
export function KillPx() {
    return $Call.ByID(2830636873);
}

/**
 * MarkStartedBySvc records that the current px was started via px-service.
 * @returns {$CancellablePromise<void>}
 */
export function MarkStartedBySvc() {
    return $Call.ByID(1390647494);
}

/**
 * OpenConfigDir opens the data directory in the OS file manager.
 * Mirrors Electron's `pxConfigDir` (shell.openPath).
 * @returns {$CancellablePromise<void>}
 */
export function OpenConfigDir() {
    return $Call.ByID(4090019930);
}

/**
 * PxPath returns the resolved px binary path.
 * @returns {$CancellablePromise<string>}
 */
export function PxPath() {
    return $Call.ByID(3778299366);
}

/**
 * RestartDirect kills any running px and spawns a fresh one directly (no
 * elevated service). Used on first start and for non-TUN restarts.
 * @returns {$CancellablePromise<$models.ConnInfo>}
 */
export function RestartDirect() {
    return $Call.ByID(4139875253).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SelectDirectory shows a native folder picker and returns the chosen path, or
 * "" if the user cancelled. Mirrors Electron's `select-directory`.
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(650242992);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function ShowInFolder(path) {
    return $Call.ByID(3482590167, path);
}

/**
 * Start launches the callback server and the px process (direct spawn), then
 * waits until px has called back with its port/secret.
 * @returns {$CancellablePromise<$models.ConnInfo>}
 */
export function Start() {
    return $Call.ByID(1409532927).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Stop terminates px and the callback server (Wails lifecycle hook).
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(315843205);
}

// Private type creation functions
const $$createType0 = $models.ConnInfo.createFrom;
