// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnInfo is the connection information the frontend needs to talk to px.
 */
export class ConnInfo {
    /**
     * Creates a new ConnInfo instance.
     * @param {Partial<ConnInfo>} [$$source = {}] - The source object to create the ConnInfo.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("secret" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnInfo(/** @type {Partial<ConnInfo>} */($$parsedSource));
    }
}

/**
 * ServiceStatus mirrors the shape the frontend expects from window.pxService.
 */
export class ServiceStatus {
    /**
     * Creates a new ServiceStatus instance.
     * @param {Partial<ServiceStatus>} [$$source = {}] - The source object to create the ServiceStatus.
     */
    constructor($$source = {}) {
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("isAdmin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isAdmin"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServiceStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceStatus(/** @type {Partial<ServiceStatus>} */($$parsedSource));
    }
}
