// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes small OS helpers to the frontend. It is the Wails
 * replacement for the misc window.px* helpers that used to be provided by
 * src-electron/preload.ts (pxOs, pxUsername, ...).
 * 
 * Phase 0 keeps this minimal; clipboard / open-external / show-in-folder are
 * handled on the frontend via the Wails runtime in the PoC shim and will be
 * consolidated here in a later phase.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * AutostartEnabled reports whether launch-at-login is currently registered AND
 * will actually run. Registration comes from the built-in Wails v3 Autostart
 * manager (LaunchAgent / registry Run / .desktop autostart); on Windows the
 * entry can additionally be switched off in Task Manager without being removed,
 * which counts as disabled here (see autostart_approval_windows.go).
 * @returns {$CancellablePromise<boolean>}
 */
export function AutostartEnabled() {
    return $Call.ByID(3749051105);
}

/**
 * OS returns a short OS + arch string, e.g. "Linux x64".
 * @returns {$CancellablePromise<string>}
 */
export function OS() {
    return $Call.ByID(3909119865);
}

/**
 * SetAutostart enables or disables launch-at-login.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutostart(enabled) {
    return $Call.ByID(3788513814, enabled);
}

/**
 * Username returns the current user's username (best effort), matching what
 * Electron's preload reports via os.userInfo().username.
 * 
 * The bare account name is what callers need: px looks the user's SID up with
 * `Win32_UserAccount WHERE Name='<username>'` to reach their registry hive
 * (pkg/sys/proxy.getUserSID), and that query does not match a domain-qualified
 * name. user.Current() returns `DOMAIN\user` on Windows, so the prefix is
 * stripped here rather than at each call site.
 * @returns {$CancellablePromise<string>}
 */
export function Username() {
    return $Call.ByID(3066328455);
}
