// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes small OS helpers to the frontend. It is the Wails
 * replacement for the misc window.px* helpers that used to be provided by
 * src-electron/preload.ts (pxOs, pxUsername, ...).
 * 
 * Phase 0 keeps this minimal; clipboard / open-external / show-in-folder are
 * handled on the frontend via the Wails runtime in the PoC shim and will be
 * consolidated here in a later phase.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * AutostartEnabled reports whether launch-at-login is currently registered.
 * Uses the built-in Wails v3 Autostart manager (LaunchAgent / registry Run /
 * .desktop autostart).
 * @returns {$CancellablePromise<boolean>}
 */
export function AutostartEnabled() {
    return $Call.ByID(3749051105);
}

/**
 * OS returns a short OS + arch string, e.g. "Linux x64".
 * @returns {$CancellablePromise<string>}
 */
export function OS() {
    return $Call.ByID(3909119865);
}

/**
 * SetAutostart enables or disables launch-at-login.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutostart(enabled) {
    return $Call.ByID(3788513814, enabled);
}

/**
 * Username returns the current user's username (best effort).
 * @returns {$CancellablePromise<string>}
 */
export function Username() {
    return $Call.ByID(3066328455);
}
