// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TunService manages the privileged px-service helper that enables TUN mode
 * without running the whole app as administrator. It is the Wails replacement
 * for src-electron/service.ts and is bound to the frontend as window.pxService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetStatus reports installed/running/admin state of the px-service.
 * 
 * "Installed" means registered with the OS service manager — NOT merely that
 * the bundled px-service binary is present on disk, which it always is. The
 * frontend uses this to decide whether to offer installing the service and
 * whether a restart-through-the-service recovery is worth attempting
 * (MyProxy.vue), so the file-presence answer made it skip both.
 * @returns {$CancellablePromise<$models.ServiceStatus>}
 */
export function GetStatus() {
    return $Call.ByID(2324469595).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Install installs the px-service (requires elevation) and waits for it to
 * come up. Returns true if the service is reachable afterwards.
 * @returns {$CancellablePromise<boolean>}
 */
export function Install() {
    return $Call.ByID(423465926);
}

/**
 * IsRunning reports whether the px-service IPC endpoint is reachable.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRunning() {
    return $Call.ByID(292128210);
}

/**
 * RestartBackend restarts px. If the service is running, px is (re)started
 * through the elevated service so it can manage TUN; otherwise it is spawned
 * directly. Returns the fresh connection info for the frontend.
 * @returns {$CancellablePromise<$models.ConnInfo>}
 */
export function RestartBackend() {
    return $Call.ByID(4022468298).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ShowInstallDialog asks the user whether to install the TUN service.
 * Returns "install", "skip" or "cancel".
 * @returns {$CancellablePromise<string>}
 */
export function ShowInstallDialog() {
    return $Call.ByID(2500079301);
}

/**
 * StartBackend is the application startup entry point for launching px. When the
 * privileged px-service is reachable it routes px through the service so TUN can
 * work without running the GUI as administrator — mirroring src-electron
 * admin.ts. If TUN was enabled last session and the OS reports the service as
 * starting, it waits briefly for it, covering the boot race where the
 * autostarted (non-elevated) app launches px before the service has finished
 * starting. If the service never comes up (or isn't installed) px is spawned
 * directly.
 * @returns {$CancellablePromise<$models.ConnInfo>}
 */
export function StartBackend() {
    return $Call.ByID(1625403615).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Uninstall removes the px-service (requires elevation).
 * 
 * px is stopped through the service FIRST: while the service is installed it
 * owns the running px (spawned as root/LocalSystem, so the shell cannot signal
 * it). Removing the service without stopping px left an orphaned privileged
 * process holding the control port and the TUN device, and the freshly spawned
 * unprivileged px then had to fall back to a random port.
 * @returns {$CancellablePromise<boolean>}
 */
export function Uninstall() {
    return $Call.ByID(2861672307);
}

// Private type creation functions
const $$createType0 = $models.ServiceStatus.createFrom;
const $$createType1 = $models.ConnInfo.createFrom;
